[package]
name = "tinyraytracer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.51"
fehler = "1.0.0"
glam = "0.20.1"
